environment:
  nodejs_version: "Current"

install:
- ps: Install-Product node $env:nodejs_version

- appveyor-retry npm install -g npm@latest
- appveyor-retry npm install

test_script:
- npm test

build: off
